# Generated by Django 4.2.7 on 2023-11-14 16:15

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_remove_trainer_course_course_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(default='', max_length=100)),
                ('student', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Email', models.CharField(default='', max_length=100)),
                ('alternative_email', models.EmailField(blank=True, help_text='not compulsory.', max_length=254, null=True)),
                ('Adress', models.CharField(default='', max_length=100)),
                ('Alternative_adress', models.CharField(blank=True, help_text='not compulsory.', max_length=100, null=True)),
                ('DOB', models.DateField(default='')),
                ('mobile', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('whatsapp_num', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('collage_name', models.CharField(default='', max_length=100)),
                ('year_of_pass_out', models.PositiveIntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)])),
                ('qualification', models.CharField(default='', max_length=100)),
                ('roll_num', models.CharField(default='', max_length=100)),
                ('reg_num', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(default='', upload_to='photo/')),
                ('student_call_status', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], max_length=4)),
                ('next_follow_up_date', models.DateField(default='')),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.course')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.districts')),
                ('enquiry_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.enquiry_source')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.states')),
                ('to_staff', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='settings.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('does_this_student_have_laptop', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.batch')),
            ],
        ),
    ]
