# Generated by Django 4.2.7 on 2023-11-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENTS', '0002_alter_students_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENTS.students'),
        ),
    ]
